### ISSUE TITLE
Additional https:// string added as prefix to values in endpoint variable

### ISSUE THREAD

**Issue by AT2406** [grafana/xk6-output-opentelemetry#19]
In my job I pull in an ssm parameter which is set to the http exporter endpoint variable, example below. 

`$ echo $K6_OTEL_HTTP_EXPORTER_ENDPOINT
https://otlp.dummyurl.io/
`

But for some reason when i try to use this when i run my tests in a pipeline it looks like an additional https:// is added to the front of the endpoint when it exists already resulting in the error shown below

`time="2024-08-01T08:42:01Z" level=error msg="failed to create OpenTelemetry exporter: parse \"https://https:%2F%2Fotlp.dummyurl.io/v1/metrics\": invalid port \":%2F%2Fotlp.dummyurl.io\" after host"
`

I have ended up stripping the string from the variable after i get the values from ssm but t might be worth having an if statement that checks for if the passed in value has the https prefix already or not

**Comment by mstoykov** [comment]
Hi @AT2406, thanks for reporting this :bow: 

 I have looked into this and it seems like any implementaiton where this is done automatically will conflict with K6_OTEL_HTTP_EXPORTER_INSECURE and looking at the code this all comes from how OTEL API and their env variables are defined.

I have opened https://github.com/grafana/xk6-output-opentelemetry/pull/20 to at least check for this case
